<%@ page contentType="text/html; charset=UTF-8" %><p>title: xx
date : 2018/1/31</p>
<hr />
<pre><code class="language-java"> if (this == MULTI_MARKDOWN) {
    return new MutableListOptions().setParserEmulationFamily(this)
            .setAutoLoose(true)
            .setAutoLooseOneLevelLists(true)
            .setDelimiterMismatchToNewList(false)
            .setCodeIndent(8)
            .setEndOnDoubleBlank(false)
            .setItemIndent(4)
            .setItemInterrupt(new ListOptions.MutableItemInterrupt()
                    .setBulletItemInterruptsParagraph(false)
                    .setOrderedItemInterruptsParagraph(false)
                    .setOrderedNonOneItemInterruptsParagraph(false)

                    .setEmptyBulletItemInterruptsParagraph(false)
                    .setEmptyOrderedItemInterruptsParagraph(false)
                    .setEmptyOrderedNonOneItemInterruptsParagraph(false)

                    .setBulletItemInterruptsItemParagraph(true)
                    .setOrderedItemInterruptsItemParagraph(true)
                    .setOrderedNonOneItemInterruptsItemParagraph(true)

                    .setEmptyBulletItemInterruptsItemParagraph(true)
                    .setEmptyOrderedItemInterruptsItemParagraph(true)
                    .setEmptyOrderedNonOneItemInterruptsItemParagraph(true)

                    .setEmptyBulletSubItemInterruptsItemParagraph(true)
                    .setEmptyOrderedSubItemInterruptsItemParagraph(true)
                    .setEmptyOrderedNonOneSubItemInterruptsItemParagraph(true)
            )
            .setItemMarkerSpace(false)
            .setItemTypeMismatchToNewList(false)
            .setItemTypeMismatchToSubList(false)
            .setLooseWhenBlankLineFollowsItemParagraph(true)
            .setLooseWhenHasTrailingBlankLine(false)
            .setLooseWhenHasNonListChildren(true)
            .setNewItemCodeIndent(Integer.MAX_VALUE)
            .setOrderedItemDotOnly(true)
            .setOrderedListManualStart(false)
            ;
}
if (this == PEGDOWN || this == PEGDOWN_STRICT) {
    return new MutableListOptions().setParserEmulationFamily(this)
            .setAutoLoose(false)
            .setAutoLooseOneLevelLists(false)
            .setLooseWhenBlankLineFollowsItemParagraph(false)
            .setLooseWhenHasLooseSubItem(false)
            .setLooseWhenHasTrailingBlankLine(false)
            .setLooseWhenPrevHasTrailingBlankLine(true)
            .setOrderedListManualStart(false)
            .setDelimiterMismatchToNewList(false)
            .setItemTypeMismatchToNewList(true)
            .setItemTypeMismatchToSubList(false)
            .setEndOnDoubleBlank(false)
            .setOrderedItemDotOnly(true)
            .setItemMarkerSpace(true)
            .setItemIndent(4)
            .setCodeIndent(8)
            .setNewItemCodeIndent(Integer.MAX_VALUE)
            .setItemInterrupt(new ListOptions.MutableItemInterrupt()
                    .setBulletItemInterruptsParagraph(false)
                    .setOrderedItemInterruptsParagraph(false)
                    .setOrderedNonOneItemInterruptsParagraph(false)

                    .setEmptyBulletItemInterruptsParagraph(false)
                    .setEmptyOrderedItemInterruptsParagraph(false)
                    .setEmptyOrderedNonOneItemInterruptsParagraph(false)

                    .setBulletItemInterruptsItemParagraph(true)
                    .setOrderedItemInterruptsItemParagraph(true)
                    .setOrderedNonOneItemInterruptsItemParagraph(true)

                    .setEmptyBulletItemInterruptsItemParagraph(true)
                    .setEmptyOrderedItemInterruptsItemParagraph(true)
                    .setEmptyOrderedNonOneItemInterruptsItemParagraph(true)

                    .setEmptyBulletSubItemInterruptsItemParagraph(true)
                    .setEmptyOrderedSubItemInterruptsItemParagraph(true)
                    .setEmptyOrderedNonOneSubItemInterruptsItemParagraph(true)
            );
}
return new MutableListOptions().setParserEmulationFamily(this)
        .setAutoLoose(false)
        .setAutoLooseOneLevelLists(false)
        .setLooseWhenBlankLineFollowsItemParagraph(false)
        .setLooseWhenHasLooseSubItem(false)
        .setLooseWhenHasTrailingBlankLine(true)
        .setLooseWhenPrevHasTrailingBlankLine(false)
        .setLooseWhenLastItemPrevHasTrailingBlankLine(true)
        .setOrderedListManualStart(false)
        .setDelimiterMismatchToNewList(false)
        .setItemTypeMismatchToNewList(false)
        .setItemTypeMismatchToSubList(false)
        .setEndOnDoubleBlank(false)
        .setOrderedItemDotOnly(true)
        .setItemMarkerSpace(true)
        .setItemIndent(4)
        .setCodeIndent(8)
        .setNewItemCodeIndent(Integer.MAX_VALUE)
        .setItemInterrupt(new ListOptions.MutableItemInterrupt()
                .setBulletItemInterruptsParagraph(false)
                .setOrderedItemInterruptsParagraph(false)
                .setOrderedNonOneItemInterruptsParagraph(false)

                .setEmptyBulletItemInterruptsParagraph(false)
                .setEmptyOrderedItemInterruptsParagraph(false)
                .setEmptyOrderedNonOneItemInterruptsParagraph(false)

                .setBulletItemInterruptsItemParagraph(true)
                .setOrderedItemInterruptsItemParagraph(true)
                .setOrderedNonOneItemInterruptsItemParagraph(true)

                .setEmptyBulletItemInterruptsItemParagraph(true)
                .setEmptyOrderedItemInterruptsItemParagraph(true)
                .setEmptyOrderedNonOneItemInterruptsItemParagraph(true)

                .setEmptyBulletSubItemInterruptsItemParagraph(true)
                .setEmptyOrderedSubItemInterruptsItemParagraph(true)
                .setEmptyOrderedNonOneSubItemInterruptsItemParagraph(true)
        );
}
if (family == KRAMDOWN) {
return new MutableListOptions()
        .setParserEmulationFamily(this)
        .setAutoLoose(false)
        .setLooseWhenBlankLineFollowsItemParagraph(true)
        .setLooseWhenHasLooseSubItem(false)
        .setLooseWhenHasTrailingBlankLine(false)
        .setLooseWhenPrevHasTrailingBlankLine(false)
        .setOrderedListManualStart(false)
        .setDelimiterMismatchToNewList(false)
        .setItemTypeMismatchToNewList(true)
        .setItemTypeMismatchToSubList(true)
        .setOrderedItemDotOnly(true)
        .setItemMarkerSpace(true)
        .setEndOnDoubleBlank(false)
        .setItemIndent(4)
        .setCodeIndent(8)
        .setNewItemCodeIndent(Integer.MAX_VALUE)
        .setItemInterrupt(new ListOptions.MutableItemInterrupt()
                .setBulletItemInterruptsParagraph(false)
                .setOrderedItemInterruptsParagraph(false)
                .setOrderedNonOneItemInterruptsParagraph(false)

                .setEmptyBulletItemInterruptsParagraph(false)
                .setEmptyOrderedItemInterruptsParagraph(false)
                .setEmptyOrderedNonOneItemInterruptsParagraph(false)

                .setBulletItemInterruptsItemParagraph(true)
                .setOrderedItemInterruptsItemParagraph(true)
                .setOrderedNonOneItemInterruptsItemParagraph(true)

                .setEmptyBulletItemInterruptsItemParagraph(true)
                .setEmptyOrderedItemInterruptsItemParagraph(true)
                .setEmptyOrderedNonOneItemInterruptsItemParagraph(true)

                .setEmptyBulletSubItemInterruptsItemParagraph(false)
                .setEmptyOrderedSubItemInterruptsItemParagraph(false)
                .setEmptyOrderedNonOneSubItemInterruptsItemParagraph(false)
        );
}
if (family == MARKDOWN) {
if (this == GITHUB_DOC) {
    return new MutableListOptions()
            .setParserEmulationFamily(this)
            .setAutoLoose(false)
            .setLooseWhenBlankLineFollowsItemParagraph(true)
            .setLooseWhenHasLooseSubItem(true)
            .setLooseWhenHasTrailingBlankLine(true)
            .setLooseWhenPrevHasTrailingBlankLine(true)
            .setLooseWhenContainsBlankLine(false)
            .setLooseWhenHasNonListChildren(true)
            .setOrderedListManualStart(false)
            .setDelimiterMismatchToNewList(false)
            .setItemTypeMismatchToNewList(false)
            .setItemTypeMismatchToSubList(false)
            .setEndOnDoubleBlank(false)
            .setOrderedItemDotOnly(true)
            .setItemMarkerSpace(true)
            .setItemIndent(4)
            .setCodeIndent(8)
            .setNewItemCodeIndent(Integer.MAX_VALUE)
            .setItemInterrupt(new ListOptions.MutableItemInterrupt()
                    .setBulletItemInterruptsParagraph(true)
                    .setOrderedItemInterruptsParagraph(false)
                    .setOrderedNonOneItemInterruptsParagraph(false)

                    .setEmptyBulletItemInterruptsParagraph(true)
                    .setEmptyOrderedItemInterruptsParagraph(false)
                    .setEmptyOrderedNonOneItemInterruptsParagraph(false)

                    .setBulletItemInterruptsItemParagraph(true)
                    .setOrderedItemInterruptsItemParagraph(true)
                    .setOrderedNonOneItemInterruptsItemParagraph(true)

                    .setEmptyBulletItemInterruptsItemParagraph(true)
                    .setEmptyOrderedItemInterruptsItemParagraph(true)
                    .setEmptyOrderedNonOneItemInterruptsItemParagraph(true)

                    .setEmptyBulletSubItemInterruptsItemParagraph(true)
                    .setEmptyOrderedSubItemInterruptsItemParagraph(true)
                    .setEmptyOrderedNonOneSubItemInterruptsItemParagraph(true)
            );
}

</code></pre>
<pre><code class="language-java">if (this == GITHUB_DOC) {
    return new MutableListOptions()
            .setParserEmulationFamily(this)
            .setAutoLoose(false)
            .setLooseWhenBlankLineFollowsItemParagraph(true)
            .setLooseWhenHasLooseSubItem(true)
            .setLooseWhenHasTrailingBlankLine(true)
            .setLooseWhenPrevHasTrailingBlankLine(true)
            .setLooseWhenContainsBlankLine(false)
            .setLooseWhenHasNonListChildren(true)
            .setOrderedListManualStart(false)
            .setDelimiterMismatchToNewList(false)
            .setItemTypeMismatchToNewList(false)
            .setItemTypeMismatchToSubList(false)
            .setEndOnDoubleBlank(false)
            .setOrderedItemDotOnly(true)
            .setItemMarkerSpace(true)
            .setItemIndent(4)
            .setCodeIndent(8)
            .setNewItemCodeIndent(Integer.MAX_VALUE)
            .setItemInterrupt(new ListOptions.MutableItemInterrupt()
                    .setBulletItemInterruptsParagraph(true)
                    .setOrderedItemInterruptsParagraph(false)
                    .setOrderedNonOneItemInterruptsParagraph(false)

                    .setEmptyBulletItemInterruptsParagraph(true)
                    .setEmptyOrderedItemInterruptsParagraph(false)
                    .setEmptyOrderedNonOneItemInterruptsParagraph(false)

                    .setBulletItemInterruptsItemParagraph(true)
                    .setOrderedItemInterruptsItemParagraph(true)
                    .setOrderedNonOneItemInterruptsItemParagraph(true)

                    .setEmptyBulletItemInterruptsItemParagraph(true)
                    .setEmptyOrderedItemInterruptsItemParagraph(true)
                    .setEmptyOrderedNonOneItemInterruptsItemParagraph(true)

                    .setEmptyBulletSubItemInterruptsItemParagraph(true)
                    .setEmptyOrderedSubItemInterruptsItemParagraph(true)
                    .setEmptyOrderedNonOneSubItemInterruptsItemParagraph(true)
            );
}
</code></pre>
